server:
  port: 9000

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
      show-components: always
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        all: true
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0
  prometheus:
    metrics:
      export:
        step: 10s
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true

spring:
  application:
    name: edge-service

  cloud:
    gateway:
      default-filters:
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
      routes:
        - id: product-route
          uri: ${PRODUCT_SERVICE_URL:http://172.18.224.1:9001}
          predicates:
            - Path=/products/**
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
            - name: CircuitBreaker
              args:
                name: productService
                fallbackUri: forward:/books-fallback
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms                  
        - id: order-route        
          uri: ${ORDER_SERVICE_URL:http://172.18.224.1:9002}
          predicates:
            - Path=/orders/**
          filters:
            - AddRequestHeader=X-Tenant,acme
            - AddResponseHeader=X-Genre,fantasy
            - name: CircuitBreaker
              args:
                name: orderService
                fallbackUri: forward:/orders-fallback
            - name: Retry
              args:
                retries: 3
                method: GET
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms		  

resilience4j:
  circuitbreaker:
    instances:
      productService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true
      orderService:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
        registerHealthIndicator: true 
  timelimiter:
    instances:
      bookService:
        timeoutDuration: 3s
